services:

    wordpress:
        container_name: wordpress_skeleton_vscode
        image: wordpress_skeleton_vscode
        build:
            context: .devcontainer
            dockerfile: Dockerfile
        ports:
            - 9090:80
        volumes:
            - ./config/docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./config/wordpress/wp-config.dev.php:/var/www/html/wp-config.dev.php
            - .:/var/www/html/wp-content/plugins/skeleton
                
